### ISSUE TITLE
iOS 13 fields fail to focus

### ISSUE THREAD

**Issue by AnthonySmith01** [onderceylan/cordova-plugin-wkwebview-inputfocusfix#10]
Hi

Thanks for this great plugin.

I just noticed that when running on iOS 13 this error appears:
CDVPlugin class WKWebViewInputFocusFix (pluginName: wkwebviewinputfocusfix) does not exist.

Focusing also doesn't happen. On other iOS versions it still works though. Build phases also has the CDVWKWebViewEngine+InputFocusFix.m file listed.

**Comment by AnthonySmith01** [comment]
Actually, that CDVPlugin class error occurs on all versions. Although iOS 13 still does not focus / display the keyboard.

I'm assuming that Webkit may have changed the method signature again? Although I don't know how to investigate this.

**Comment by dlbass** [comment]
We are seeing the same error message, and the inputs do not focus on iOS 12.3.1

**Comment by onderceylan** [comment]
Hi @AnthonySmith01 and @dlbass, I'm sorry if it wasn't clear from the docs of the plugin but this cordova plugin has no use anymore. 

The same changes within this plugin is merged into main repository of wkwebview https://github.com/apache/cordova-plugin-wkwebview-engine. Please submit any issues related to input focussing here https://github.com/apache/cordova-plugin-wkwebview-engine/issues.
