### ISSUE TITLE
Broken on iOS 11.3

### ISSUE THREAD

**Issue by hirbod** [onderceylan/cordova-plugin-wkwebview-inputfocusfix#3]
Hi @onderceylan,

just upgraded to iOS 11.3 today and this hack/fix does not work anymore. Do you have a quick fix for it? Would be awesome. Thank you!

**Comment by hirbod** [comment]
Here is a fix

https://stackoverflow.com/a/48623286/3297914

**Comment by hirbod** [comment]
Provided a PR #4, could you merge please and submit this fix to npm? Thanks!

**Comment by hirbod** [comment]
Well, feel free to close or merge, as my PR was also ported to
https://github.com/ionic-team/cordova-plugin-ionic-webview/commit/5ad40ae6b456a0e7edc7f48a307ac2fe52919914

**Comment by onderceylan** [comment]
Hi Hirbod, thanks for the update. I'll merge your PR with also noting this repo should be out of use since that workaround is not needed anymore.

**Comment by onderceylan** [comment]
Merged PR #4, thanks!
