### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by ccorcos** [onderceylan/cordova-plugin-wkwebview-inputfocusfix#6]
Why does +load get called and how does this plugin work? Is there a name for this approach that I can look up on the internet to learn more about it?

Thanks

**Comment by onderceylan** [comment]
Hi @ccorcos,

This is called Customizing in obj c. You can see related docs here:

https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html

Please see "Consider Other Alternatives for Class Customization" section over there. I don't recommend this approach unless you have to.
